export enum NotificationTypes{
    SEND_TO_ALL = 'SEND_TO_ALL',
    // Notifications to DRIVERS
    TRANSFER_BOOKING = 'TRANSFER_BOOKING',
    TRANSFER_BOOKING_ALL = 'TRANSFER_BOOKING_ALL',
    LEARNER_BOOKING_CONFIRMATION = 'LEARNER_BOOKING_CONFIRMATION',
    // Notifications to LEARNERS
    INSTRUCTOR_CHANGED = 'INSTRUCTOR_CHANGED',
    RATE_DRIVER = 'RATE_DRIVER',
    TEST_CENTER_CONFIRMED = "TEST_CENTER_CONFIRMED",
    LEARNER_BOOKING_TIME  = "LEARNER_BOOKING_TIME"
}